[workspace]

[package]
name = "turtle"
version = "1.0.0-alpha.6"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]
description = "Turtle Graphics in Rust"
homepage = "http://turtle.rs"
repository = "https://github.com/sunjay/turtle"
readme = "README.md"
keywords = ["turtle", "graphics", "drawing", "teaching", "beginner"]
# crates.io/category_slugs
categories = ["rendering", "rendering::graphics-api", "rendering::engine", "games", "gui"]
license = "MIT"

[badges]
# Appveyor: `repository` is required. `branch` is optional; default is `master`
appveyor = { repository = "sunjay/turtle" }

# Travis CI: `repository` in format "<user>/<project>" is required.
travis-ci = { repository = "sunjay/turtle" }

# Is it maintained resolution time: `repository` is required.
is-it-maintained-issue-resolution = { repository = "sunjay/turtle" }

# Is it maintained percentage of open issues: `repository` is required.
is-it-maintained-open-issues = { repository = "sunjay/turtle" }

[dependencies]
piston_window = "^0.73.0"
interpolation = "^0.1.0"
rand = "^0.3.18"
turtle-canvas = { path = "turtle-canvas" }

# The reason we do this is because doctests don't get cfg(test)
# See: https://github.com/rust-lang/cargo/issues/4669
#
# This allows us to write attributes like the following and have it work
# in all tests.
#
# #[cfg(any(feature = "test", test))]
#
# NOTE: This means that tests MUST be run with:
#   cargo test --features "test"
[features]
test = []
