[package]
name = "turtle-canvas"
version = "0.1.0"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
piston_window = "^0.73.0"
interpolation = "^0.1.0"
rand = "^0.3.18"
